import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/lib/auth";
import Navbar from "@/components/navbar/navbar";

const playfair_display = Playfair_Display({
  variable: "--font-playfair_display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();

  return (
    <html
      lang="en"
      className={`${playfair_display.variable} antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SessionProvider session={session}>
          {/* <Navbar/> */}
          <main className="bg-gray-50 min-h-screen">
            {children}
          </main>
        </SessionProvider>
      </body>

    </html>
  );
}
